apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: to-do-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: to-do-app=446853875456.dkr.ecr.ap-northeast-2.amazonaws.com/to-do-app
    argocd-image-updater.argoproj.io/to-do-app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/SabioBox/to-do-app.git
    targetRevision: HEAD
    path: .
    kustomize:
      namePrefix: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

